### PR TITLE
Fix to match return of get_image_type to imghdr.what

### PR DESCRIPTION
**Pull request by takeokt**
Hi Kevin,

I have modified to the type of return value from unicode to byte string in python 2.

Please merge my fork of the KindleUnpack.

Take care,
tkeo

### CODE REVIEW

**Comment by kevinhendricks** [comment]
Hi tkeo,

No, I would rather the interface always return the string as full unicode instead of mixing return types.  So we simply coerce to unicode and change downstream users to understand that.  The general rule in KindleUnpack is that the only time a byte string is used is when it is the *only* way to handle things  because byte offset file position information is needed (and therefore must be preserved ) when decoding mixed binary data.

Thanks,

Kevin

**Comment by takeokt** [comment]
Hi Kevin,

OK. The return value of get_image_type() is all ways unicode on python 3. On python 2, it is byte string if it is from imghdr.what(), however, it is assigned as a unicode in get_image_type(). Should them be unified to unicode?

Thanks,
tkeo

**Comment by kevinhendricks** [comment]
Hi,
Yes import unicodestr from compatibility_utils and use it to fix things as returning.

Then verify the all downstream calls to get_image_type treat it as full unicode (I think they already do but it can't hurt to doublecheck.

Thanks,

Kevin

**Comment by takeokt** [comment]
Hi,
OK. I will do.

Thanks,

**Pull request closed without merging**
