### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `typos --hidden --format brief`

### CODE REVIEW

**Comment by kevinhendricks** [comment]
Only fixes for typos in actual code (not typos comments) will be accepted since changes in comments are unnecessary and just clutter up actual change histories.

If you remove all changes to comments, I would be happy to look merging in a PR.

**Comment by kianmeng** [comment]
@kevinhendricks Done.

**Comment by kevinhendricks** [comment]
Thank you!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
