### PR TITLE
Markdown bullet cleanup in readme

### PR DESCRIPTION
**Pull request by clach04**
Working bullet points instead of code block

### CODE REVIEW

**Comment by kevinhendricks** [comment]
Thank you.  But minor subjective whitespace changes will not be made.

**Comment by clach04** [comment]
> Thank you. But minor subjective whitespace changes will not be made.

Can you clarify? These implement working bullet points, the opposite of `subjective whitespace`. It's significant, not subjective in Markdown. The current readme is not readable on mobile with the pre-formatted code block that's currently in use due to the lack of line wrapping.

Compare current:

    - MobiPocket and early Kindle version 7 or less ebooks are unpacked to the 
            original html 3.2 and images folder that can then be edited and reprocessed by 
            MobiPocketCreator.
    
    - Kindle Print Replica ebook are unpacked to the original PDF and any associated images.
    
    - Kindle KF8 only ebooks (.azw3) are unpacked into an epub-like structure that may or 
            may not be a fully valid epub depending on if a fully valid epub was 
            originally provided to kindlegen as input.  NOTE: The generated epub should be
            validated using an epub validator and should changes be needed, it should load
            properly into Sigil and Calibre either of which can be used to edit the result
            to create a fully valid epub.
    
    - Newer Kindle ebooks which have both KF8 and older versions inside are unpacked into 
            two different parts: the first being the older MobiPocket format ebook parts 
            and the second being an epub-like structure that can be edited using Sigil

proposed:

- MobiPocket and early Kindle version 7 or less ebooks are unpacked to the 
        original html 3.2 and images folder that can then be edited and reprocessed by 
        MobiPocketCreator.

- Kindle Print Replica ebook are unpacked to the original PDF and any associated images.

- Kindle KF8 only ebooks (.azw3) are unpacked into an epub-like structure that may or 
        may not be a fully valid epub depending on if a fully valid epub was 
        originally provided to kindlegen as input.  NOTE: The generated epub should be
        validated using an epub validator and should changes be needed, it should load
        properly into Sigil and Calibre either of which can be used to edit the result
        to create a fully valid epub.

- Newer Kindle ebooks which have both KF8 and older versions inside are unpacked into 
        two different parts: the first being the older MobiPocket format ebook parts 
        and the second being an epub-like structure that can be edited using Sigil

**Comment by kevinhendricks** [comment]
It was always formatted that way so the file can be read as a simple text file as well.

**Comment by clach04** [comment]
> It was always formatted that way so the file can be read as a simple text file as well.

I'm still not understanding. You deliberately chose markdown as the format, this allows reading as a simple text file. But when generating HTML (the default behavior when viewing this repo in a web browser on GitHub), the current markup in place is not readable on small screens due to the current whitespace-significant formatting as it's a pre-formatted code block.

I can see other places in the readme use code blocks, they make sense. Those changes were added in https://github.com/kevinhendricks/KindleUnpack/commit/3ce3dc77b3c7ec9633733dbea9c5295899816f77

It looks like the original intent was to have bullet points.

Thanks for making this available, I've been taking a few books apart this evening to format shift them. It's been working great  :-)

**Comment by kevinhendricks** [comment]
It is an old pre-formatted text file not worth changing just to support mobile devices for whitespace.

If you want to contribute, focus on reporting or fixing true bugs in python3 code not on things that have not mattered for the last 10 years.

**Comment by dougmassay** [comment]
Github's markdown is always in flux. What rendered correctly yesterday does
not always render correctly today. We're choosing not to chase it. The file
is readable.

**Pull request closed without merging**
